### ISSUE TITLE
pyobjc is required

### ISSUE THREAD

**Issue by cades** [KELiON/cerebro-osx-define#2]
Thanks for this cool plugin! However, I struggled for a while to get it working. At first, it just shows "Can't fetch dictionary results.". So I search this message in this repo, and find out it runs python script. Then I run it directly from my terminal -- gotcha!

```
Traceback (most recent call last):
  File "./dict.py", line 4, in <module>
    import DictionaryServices
ImportError: No module named DictionaryServices
```

I think we should note in README that user needs to `pip install pyobjc` first, or print "pyobjc is not installed" directly on Cerebro.

**Comment by KELiON** [comment]
@cades thanks for report! 

Actually, I thought that it is installed in MacOS by default. In this case I'd rewrite this plugin to use nodobjc instead of pyobc, because nodobjc is included in Cerebro

**Comment by cades** [comment]
nodobjc sounds a good direction to go 👍

**Comment by hardyoyo** [comment]
:-) it's been a few years, this bug still seems to be open, and running `pip install pyobjc` doesn't fix this error message for me:
>Can't fetch dictionary results.

**Comment by linonetwo** [comment]
This plugin is still not working.

**Comment by linonetwo** [comment]
> Then I run it directly from my terminal -- gotcha!

And python script has syntax error

```
    print dictresult.encode('utf-8')
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
```

```
    import DictionaryServices
ModuleNotFoundError: No module named 'DictionaryServices'
```

**Comment by linonetwo** [comment]
Also https://pypi.org/project/pyobjc-framework-DictionaryServices/

Deprecated wrappers for the “DictionaryServices” framework on macOS 10.5 or later.

Use package “CoreServices” instead.

**Comment by linonetwo** [comment]
I manually update the python script to

```py
# -*- coding: utf-8 -*-

import sys
import DictionaryServices

def main():
    searchword = sys.argv[1]
    wordrange = (0, len(searchword))
    dictresult = DictionaryServices.DCSCopyTextDefinition(None, searchword, wordrange)
    print(dictresult.encode('utf-8'))

if __name__ == '__main__':
    main()
```

And install ojbc like

```
python -m pip install pyobjc 
```
and it works.

Note that install via `python install pyobjc` is not working. It will install things to `/opt/anaconda3/lib/python3.7/site-packages` which is weird. And adding

```
import sys
sys.path.append("/usr/local/lib/python3.7/site-packages")
import DictionaryServices
```

won't work either.
