### ISSUE TITLE
Can't seem to find this plugin in Cerebro

### ISSUE THREAD

**Issue by tonglil** [KELiON/cerebro-osx-define#4]
This plugin does not show up in Cerebro:

<img width="1141" alt="image" src="https://cloud.githubusercontent.com/assets/3250776/23495047/83e67432-fee4-11e6-9851-cc3bd43cc7c6.png">

**Comment by KELiON** [comment]
@tonglil it was a problem in main cerebro code, solved [here](https://github.com/KELiON/cerebro/pull/194)
